name: Compile package
on: [push]
jobs:
  build_package:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX file
        uses: xu-cheng/latex-action@v4
        with:
          root_file: reptheorem.dtx
      - name: Move files into folder
        run: |
          mv reptheorem.dtx reptheorem/reptheorem.dtx
          mv reptheorem.ins reptheorem/reptheorem.ins
          mv README.md reptheorem/README.md
          mv reptheorem.pdf reptheorem/reptheorem-doc.pdf
      - name: Zip CTAN files
        uses: actions/upload-artifact@v4
        with:
          name: CTAN-files
          path: reptheorem/
      - name: Zip sty file
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: reptheorem.sty
